@ROUND=1
@GAME_NAME=GAME_01

POST http://localhost:8080/game/init
Content-Type: application/json

{
  "gameName": "{{GAME_NAME}}",
  "aliases": [
    "Gregor",
    "Rada",
    "Kuki",
    "Vito",
    "Nezka",
    "Petra"
  ]
}


###
POST http://localhost:8080/game/{{GAME_NAME}}/round/predict
Content-Type: application/json

{
  "Gregor": {{ROUND}},
  "Rada": 0,
  "Kuki": 0,
  "Vito": 0,
  "Nezka": 0,
  "Petra": 0
}

###
POST http://localhost:8080/game/{{GAME_NAME}}/round/result
Content-Type: application/json

{
  "Gregor": {{ROUND}},
  "Rada": 0,
  "Kuki": 0,
  "Vito": 0,
  "Nezka": 0,
  "Petra": 0
}